version: '3.9'
services:
  web:
    build: ./
    container_name: web_blog
    command: python manage.py runserver 0.0.0.0:4000
    #python manage.py runserver 0.0.0.0:4000
    #gunicorn blog.wsgi:application --bind 0.0.0.0:4000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 4000:4000
  db:
    image: postgres:12.0-alpine
    container_name: db_blog
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
volumes:
  postgres_data: